### PR TITLE
Custom recipe execution

### LINKED ISSUE #9: Enable custom recipe execution
Currently the `reset-tenant` tool can only execute recipes that it loads from the local [src/recipes](/src/recipes) directory. However, it would be useful to be able to execute an external recipe if it was provided. Use cases for this include creating recipes for samples or even demos for customers. 

For the CLI, it could performed as simply as:

```bash
$ reset-tenant my-recipe.js
```

Which would run the tool's TUI and show that recipe as an option in the list, probably checked by default:

```
auth0-reset-tenant, version 1.3.3
An Auth0 CLI tool/extension that can be used to reset an Auth0 tenant to a known set of artifacts.
Target Auth0 domain: peter-demo.auth0.com
[.env file: /Users/peter/.auth0-reset-tenant-env]

Recipes:
0: [x] Clear: Removes all entities from the tenant (including webtasks/extensions) and puts settings back to their defaults
1: [ ] API Authentication & Authorization: Creates a SPA that uses a database connection with a single user as well as an API
2: [ ] Demo: Multi-tenant Website Sample: Performs the Auth0 setup for the sample: https://github.com/auth0-samples/auth0-multitenant-website
3: [ ] New Tenant: Creates all the elements in a new Auth0 Tenant
4: [ ] Regular Web App: Creates a regular web app that uses a database connection with a single user
5: [x] My Recipe: A custom recipe that does something really cool
Type the recipe index to toggle, r to run, or q to quit:
```

### PR DESCRIPTION
**Pull request by twistedstream**
Closes #9 

The essence of the original feature was accomplished. The only difference is that if you do pass a custom recipe, the TUI will by default only have that recipe selected for execution. The `clear` recipe will not be selected.

This feature did required some nominal refactoring to more generically support loading of recipes from alternate sources - in the new code, the term "strategy" is used to signify different ways to do this. Two generic strategies are exported in the [src/recipes/strategies.js](https://github.com/twistedstream/auth0-reset-tenant/blob/custom-recipe-execution/src/recipes/strategies.js) module.

Builtin recipes have also been moved to the [src/recipes/builtin](https://github.com/twistedstream/auth0-reset-tenant/tree/custom-recipe-execution/src/recipes/builtin) directory in order to accommodate other scripts and directories.

Finally, all modules used by recipes have been moved to [src/recipes/lib](https://github.com/twistedstream/auth0-reset-tenant/tree/custom-recipe-execution/src/recipes/lib) for easier reference.

Here's a demo of what it looks like:
jbw2tqo2fl

### CODE REVIEW

**Comment by saltukalakus** [comment]
"Clear" code could be a library in recipes directory. There could still be a clear recipe in the builtin scripts using this library. When an external recipe is passed to auth0-reset-tenant, IMO it would be better to bypass TUI completely for recipe selection. If any external recipe needs to clean up the tenant, it could use the clear library.

**Comment by saltukalakus** [comment]
May be above comment can be considered as a new issue we can discuss later. Other than that, I couldn't notice an issue in this PR.

**Comment by twistedstream** [comment]
@saltukalakus:
> When an external recipe is passed to auth0-reset-tenant, IMO it would be better to bypass TUI completely for recipe selection.

That's a good point. If someone has an external recipe they probably only want to run that, especially since its a CLI. When this becomes an extension and you uploaded an external recipe, perhaps you'd still want to confirm the execution within the GUI.

I've been thinking about adding some command line switches that might make some of this more elegant.

For example, if you want to just run the passed in external receipt, maybe you'd pass the `--quiet` (or `-q`) switch:

```bash
reset-tenant -q my-recipe.js
```

And maybe if you wanted to silently run other builtin recipes:

```bash
reset-tenant -q --recipe clear,new_tenant
```

**Comment by twistedstream** [comment]
@saltukalakus: I also see your point about converting the `clear` recipe into a library. Because some recipes don't make sense to run additively to a tenant; the tenant should really be wiped out first. What if we just made it a property of a recipe, perhaps an export:

```js
export const name = 'New Tenant';
export const description = 'Creates all the elements in a new Auth0 Tenant';
export const clearTenant = true;
...
```

If we do this, in the TUI, it might be a good idea to warn the user before actually executing any recipe that wipes their tenant. Of course this will be bypassed if you pass the `-q` switch I mentioned in the previous comment.

**Pull request merged**
